<section class="panel">
    <form method="get" class="filter-laporan">
        <label>Jenis Arsip<select name="jenis"><option value="">Semua</option><option value="masuk" @selected(request('jenis')==='masuk')>Surat Masuk</option><option value="keluar" @selected(request('jenis')==='keluar')>Surat Keluar</option></select></label>
        <label>Tanggal Mulai<input type="date" name="mulai" value="{{ request('mulai') }}"></label><label>Tanggal Selesai<input type="date" name="selesai" value="{{ request('selesai') }}"></label><button class="tombol tombol-primer">Tampilkan</button>
    </form>
    <div class="aksi-laporan"><button class="tombol tombol-sekunder" type="button" onclick="window.print()">Export PDF</button><a class="tombol tombol-sekunder" href="{{ route('laporan.ekspor', request()->only(['jenis','mulai','selesai'])) }}">Export Excel</a></div>
    <div class="bungkus-tabel"><table><thead><tr><th>No</th><th>Jenis</th><th>No. Agenda</th><th>Perihal</th><th>Asal/Tujuan</th><th>Tanggal</th><th>Status</th></tr></thead><tbody>@forelse($surat as $item)<tr><td>{{ $loop->iteration }}</td><td>Surat {{ ucfirst($item->jenis) }}</td><td>{{ $item->nomor_agenda }}</td><td>{{ $item->perihal }}</td><td>{{ $item->pihak }}</td><td>{{ $item->tanggal_surat->format('d/m/y') }}</td><td><span class="lencana {{ strtolower($item->status) }}">{{ $item->status }}</span></td></tr>@empty<tr><td colspan="7" class="kosong">Tidak ada data pada periode ini.</td></tr>@endforelse</tbody></table></div>
</section>
@if($surat->isNotEmpty())<section class="panel preview-laporan"><h2>Preview Arsip</h2>@php $awal=$surat->first(); @endphp<div class="preview-ringkas"><div class="ikon-dokumen"><svg><use href="#i-laporan"/></svg></div><dl><dt>Jenis</dt><dd>Surat {{ ucfirst($awal->jenis) }}</dd><dt>No. Agenda</dt><dd>{{ $awal->nomor_agenda }}</dd><dt>Perihal</dt><dd>{{ $awal->perihal }}</dd><dt>Asal/Tujuan</dt><dd>{{ $awal->pihak }}</dd><dt>Tanggal Surat</dt><dd>{{ $awal->tanggal_surat->format('d/m/Y') }}</dd><dt>Status</dt><dd>{{ $awal->status }}</dd></dl><div><a class="tombol tombol-sekunder" href="{{ route('arsip.detail',$awal) }}">Lihat Arsip</a>@if($awal->file)<a class="tombol tombol-sekunder" href="{{ route('arsip.unduh',$awal) }}">Unduh Arsip</a>@endif</div></div></section>@endif
